defaults: &defaults
  app_name: "Iceylog"
  foot_html: "&copy; Iceylog."
  domain: "127.0.0.1:3000"    
  disqus_shortname: "iceskysl"
  duoshuo_shortname: "iceskysl"
  google_analytics_key: "UA-31513752-1"
  email_sender: 'no-reply@iceskysl.com'
  twitter_id: "iceskysl"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults