# config/mongo.yml

defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: iceylog-dev

test:
  <<: *defaults
  database: iceylog-test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: iceylog-pro
  # username:
  # password:
